# Generated by Django 3.1.7 on 2021-04-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20210411_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
    ]
